---
envVars:
  internalBuild:
    INTERNAL_CONFIG_REPO_PATH: "${WORKSPACE}/platform-client-sdk-internal-config"
  55bc:
    PURECLOUD_CLIENT_ID: "03b5e96f-ee0c-4fb9-bf7d-d7707a944826"
    PURECLOUD_CLIENT_SECRET: "O31aHeF8mykNMb3JE8wbgFxnPCktZxZPHAecgXdU-wc"
    PURECLOUD_ENVIRONMENT: "inindca.com"
  standard:
    DPGP_PASSPHRASE: "D0gf00d"
    ENABLE_LOGGER_COLOR: false
overrides:
  stageSettings:
    prebuild:
      preRunScripts:
        - type: shell
          path: "${COMMON_ROOT}/resources/scripts-dca/addCredToConfig.sh"
          args:
            - "${COMMON_ROOT}"
          failOnError: true
        - type: command
          command: "npm"
          args:
            - "install"
            - "fs-extra@8.1.0"
          cwd: "${COMMON_ROOT}/resources/scripts-dca/"
          failOnError: true
    postbuild:
      gitCommit: false
      publishRelease: false
      postRunScripts:
        - type: shell
          path: "${COMMON_ROOT}/resources/scripts-dca/commitCommonRepo.sh"
          args:
            - "${INTERNAL_CONFIG_REPO_PATH}"
            - "Java SDK (platform-client-internal-v2)"
            - "java"
          appendIsNewReleaseArg: true
          appendVersionArg: true
          failOnError: true
        - type: shell
          path: mavenDeploy.sh
          args:
            - platform-client-internal-v2
            - "${SDK_REPO}/build"
            - /var/build/settings.xml
            - "${DPGP_PASSPHRASE}"
            - https://purecloud.jfrog.io/purecloud/inin-release
            - inin-release
          appendIsNewReleaseArg: true
          appendVersionArg: true
          failOnError: true
        - type: shell
          path: "${COMMON_ROOT}/resources/scripts-dca/stageInternalDocs.sh"
          args:
            - "${SDK_TEMP}/docs.zip"
            - "${SDK_REPO}/version.json"
            - "${SDK_REPO}/releaseNotes.md"
            - "java"
          appendIsNewReleaseArg: true
          appendVersionArg: true
          failOnError: true
